### ISSUE TITLE
LED Limit

### ISSUE THREAD

**Issue by rbf351** [JensAndree/Glediator-from-sdcard#1] opened 2016-03-01 15:36 UTC
When trying to add more than 320 LED's you get the following error on the UNO

> Sketch uses 15,580 bytes (48%) of program storage space. Maximum is 32,256 bytes.
> Global variables use 2,201 bytes (107%) of dynamic memory, leaving -153 bytes for local variables. Maximum is 2,048 bytes.
> processing.app.debug.RunnerException: Not enough memory; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing your footprint.
>  at cc.arduino.Compiler.size(Compiler.java:319)
>  at cc.arduino.Compiler.build(Compiler.java:156)
>  at processing.app.Sketch.build(Sketch.java:1108)
>  at processing.app.Sketch.exportApplet(Sketch.java:1138)
>  at processing.app.Sketch.exportApplet(Sketch.java:1124)
>  at processing.app.Editor$DefaultExportHandler.run(Editor.java:2430)
>  at java.lang.Thread.run(Thread.java:745)
> Not enough memory; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing your footprint.﻿>

**Comment by JensAndree** [comment] 2016-03-01 20:36
Hi and thanks for the feedback!
To be honest, I've only tested it with ~200 WS2812b on an UNO so I didn't think of this since 300+ leds was out of scope when I wrote the code.

The problem is the global variable on line 16 which tries to allocate more memory than available.
`CRGB leds[NUM_LEDS];`

Sadly both global and local variables share a total of 2048 (2k) bytes on the ATMega328p and that's a hard limit which cannot be changed or circumvented...

If you are going to make big displays then I think the latest Teensy has a lot bigger SRAM, and it's also quite a lot faster, which will help with the update frequency.

Sorry I couldn't be of any help but you've simply run out of memory.

p.s There might be a way of splitting CRGB leds into a lower and upper half - thus doubling the maximum number of possible variables/leds but it will require a re-write of FastLED library to cater for this. Have a look and see if it's feasible? Sadly I haven't got the time to look at that at the moment.

**Closed as completed** 2016-03-01 20:38 UTC
Labels: question

**Comment by rbf351** [comment] 2016-03-03 13:34
You are correct. I got myself a mega yesterday, and can run 400 pixels with no errors. Only problem now is the image is rotated 90 degrees

**Comment by JensAndree** [comment] 2016-03-03 20:45
Are you certain the image wasn't rotated prior to you getting a Mega since you couldn't compile for the UNO? Have a look in the settings in Glediator and see what have caused your data to be rotated because nothing in my code will do that nor the MEGA.
Anyhow, have fun with your now adequate SRAM :)

**Comment by rbf351** [comment] 2016-03-03 20:47
100% sure the image wasn't prior. If i use glediator via serial on either the UNO or MEGA (both work) they mirror whatever i have on my PC, but if i use the SD sketch it  rotates it's 90 degrees. Very strange

**Comment by JensAndree** [comment] 2016-03-04 19:59
I have never seen this happen, and I don't own a MEGA, but I do have a Due so I tried with that one but the data was properly aligned and not rotated. I just can't think of any reason why this would happen???
Have you changed anything in the sketch? Really odd! I have no clue here...

**Comment by rbf351** [comment] 2016-03-04 22:38
Haven't touched anything in the sketch except for the number of LEDS.
